/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escitorio;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AñadirContacto extends javax.swing.JFrame {

    /**
     * Creates new form AñadirContacto
     */
    DefaultTableModel modelo = new DefaultTableModel();
    String UserCli;
    int posicion;

    
    public AñadirContacto(String user) {
        initComponents();
        UserCli=user;

    }
    
    public void despejarTexto(JTextField llave, String identificador){
    if((jtxt_cedCon.getText().equalsIgnoreCase("Ingrese cedula del Contacto") || jtxt_cedCon.getText().equalsIgnoreCase("")) && identificador.equalsIgnoreCase("A"))
        {
        llave.setText("");
        llave.setForeground(Color.BLACK);
        }
        if((jtxt_Des.getText().equalsIgnoreCase("Ingrese un Indentificativo") || jtxt_Des.getText().equalsIgnoreCase("")) && identificador.equalsIgnoreCase("B"))
        {
        llave.setText("");
        llave.setForeground(Color.BLACK);
        } 
    }
    
    
    public void llenarTexto(String exclusor)
    {
        if(jtxt_cedCon.getText().equalsIgnoreCase("") && exclusor!="A")
        {
        jtxt_cedCon.setText("Ingrese cedula del Contacto");
        jtxt_cedCon.setForeground(Color.LIGHT_GRAY);
        }
        if(jtxt_Des.getText().equalsIgnoreCase("") && exclusor!="B")
        {
        jtxt_Des.setText("Ingrese un Indentificativo");
        jtxt_Des.setForeground(Color.LIGHT_GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxt_cedCon = new javax.swing.JTextField();
        jtxt_Des = new javax.swing.JTextField();
        jbtn_Accionar = new javax.swing.JButton();
        jbtn_Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtxt_cedCon.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_cedCon.setText("Ingrese cedula del Contacto");
        jtxt_cedCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxt_cedConMouseClicked(evt);
            }
        });
        jtxt_cedCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cedConKeyTyped(evt);
            }
        });

        jtxt_Des.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_Des.setText("Ingrese un Indentificativo");
        jtxt_Des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxt_DesMouseClicked(evt);
            }
        });

        jbtn_Accionar.setText("ACEPTAR");
        jbtn_Accionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AccionarActionPerformed(evt);
            }
        });

        jbtn_Cancelar.setText("CANCELAR");
        jbtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(157, 214, 238));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO CONTACTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_cedCon, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jtxt_Des)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jbtn_Accionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_Cancelar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_cedCon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Des, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Accionar)
                    .addComponent(jbtn_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_cedConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cedConKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'){evt.consume();}
    }//GEN-LAST:event_jtxt_cedConKeyTyped

    private void jtxt_cedConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_cedConMouseClicked
        despejarTexto(jtxt_cedCon,"A");
        llenarTexto("A");
    }//GEN-LAST:event_jtxt_cedConMouseClicked

    private void jtxt_DesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_DesMouseClicked
        despejarTexto(jtxt_Des,"B");
        llenarTexto("B");
    }//GEN-LAST:event_jtxt_DesMouseClicked

    private void jbtn_AccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AccionarActionPerformed
       try {
                Conexion cc=new Conexion();
                Connection cn = cc.localhost("proy_agiles");
                String sql="INSERT INTO CONTACTOS(CED_EMP_CONT,USE_CLI_CONT,DES_CONT) VALUES('"+jtxt_cedCon.getText()+"','"+UserCli+"','"+jtxt_Des.getText()+"')";
                PreparedStatement psd = cn.prepareStatement(sql);
                int n =psd.executeUpdate();
                if(n>0)
                {
                    
                    this.setVisible(false);
                }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"La cedula ingresada no esta registrada");
                }

    }//GEN-LAST:event_jbtn_AccionarActionPerformed

    private void jbtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirContacto("san1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_Accionar;
    private javax.swing.JButton jbtn_Cancelar;
    private javax.swing.JTextField jtxt_Des;
    private javax.swing.JTextField jtxt_cedCon;
    // End of variables declaration//GEN-END:variables
}
